image: node

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install -g nuxt
  - npm install
  - rpm run generate
  artifacts:
    paths:
    - dist
  when: manual
  only:
  - master

